### ISSUE TITLE
Bug: problem with the application start

### ISSUE THREAD

**Issue by LittleWondersHandicraft** [sloukit/pydew-valley-uzh#261]
#### **Bug Description**
Missing requests library at game launch

#### Expected Behavior
The game starts after the setup instructions

#### Steps to Reproduce
Follow the [Setup instructions](https://github.com/sloukit/pydew-valley-uzh?tab=readme-ov-file#setup-instructions)
1. As instructed, clone the repository from the **master** branch to a **new** **folder**
2. Perform all steps 2 - 4
3. Game does not start

#### Additional Context

An error will appear in the console:
```PowerShell
(venv) PS D:\projects\python\pydew-valley-uzh> python main.py
pygame-ce 2.5.0 (SDL 2.30.3, Python 3.13.1)
Traceback (most recent call last):
  File "D:\projects\python\pydew-valley-uzh\main.py", line 18, in <module>
    from src.client import send_telemetry
  File "D:\projects\python\pydew-valley-uzh\src\client.py", line 5, in <module>
    import requests  # type: ignore[import-untyped]
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'requests'
(venv) PS D:\projects\python\pydew-valley-uzh>
```
To run the game, manually install the missing library in src/client.py:
```
requests==2.32.3
```

### Version

0.1.0

### Which aspect(s) of the project is this bug affecting?

area: code quality, area: dependencies

### Screenshots

![error_with_source code](https://github.com/user-attachments/assets/03b16979-0514-4534-96f8-06f554a32188)

### Relevant log output

```shell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS D:\projects\python> git clone https://github.com/sloukit/pydew-valley-uzh.git
Cloning into 'pydew-valley-uzh'...
remote: Enumerating objects: 6922, done.
remote: Counting objects: 100% (1982/1982), done.
remote: Compressing objects: 100% (382/382), done.
remote: Total 6922 (delta 1762), reused 1600 (delta 1600), pack-reused 4940 (from 3)
Receiving objects: 100% (6922/6922), 19.06 MiB | 6.48 MiB/s, done.
Resolving deltas: 100% (4783/4783), done.
PS D:\projects\python> cd .\pydew-valley-uzh\
PS D:\projects\python\pydew-valley-uzh> python -m venv venv
PS D:\projects\python\pydew-valley-uzh> venv\Scripts\activate
(venv) PS D:\projects\python\pydew-valley-uzh> pip install -r requirements.txt
Collecting PyTMX==3.32 (from -r requirements.txt (line 1))
  Using cached PyTMX-3.32-py3-none-any.whl.metadata (1.0 kB)
Collecting pathfinding==1.0.10 (from -r requirements.txt (line 2))
  Using cached pathfinding-1.0.10-py3-none-any.whl.metadata (4.6 kB)
Collecting pygame-ce==2.5.0 (from -r requirements.txt (line 3))
  Using cached pygame_ce-2.5.0-cp313-cp313-win_amd64.whl
Collecting openpyxl==3.1.5 (from -r requirements.txt (line 6))
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl==3.1.5->-r requirements.txt (line 6))
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached PyTMX-3.32-py3-none-any.whl (24 kB)
Using cached pathfinding-1.0.10-py3-none-any.whl (22 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: pathfinding, PyTMX, pygame-ce, et-xmlfile, openpyxl
Successfully installed PyTMX-3.32 et-xmlfile-2.0.0 openpyxl-3.1.5 pathfinding-1.0.10 pygame-ce-2.5.0
(venv) PS D:\projects\python\pydew-valley-uzh> pip install -r requirements-dev.txt
Collecting ruff~=0.5 (from -r requirements-dev.txt (line 1))
  Using cached ruff-0.8.4-py3-none-win_amd64.whl.metadata (25 kB)
Collecting pygbag==0.9.2 (from -r requirements-dev.txt (line 2))
  Using cached pygbag-0.9.2-py3-none-any.whl.metadata (7.4 kB)
Collecting rich==13.9.4 (from -r requirements-dev.txt (line 3))
  Using cached rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting markdown-it-py>=2.2.0 (from rich==13.9.4->-r requirements-dev.txt (line 3))
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich==13.9.4->-r requirements-dev.txt (line 3))
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich==13.9.4->-r requirements-dev.txt (line 3))
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached pygbag-0.9.2-py3-none-any.whl (171 kB)
Using cached rich-13.9.4-py3-none-any.whl (242 kB)
Using cached ruff-0.8.4-py3-none-win_amd64.whl (9.7 MB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: ruff, pygments, pygbag, mdurl, markdown-it-py, rich
Successfully installed markdown-it-py-3.0.0 mdurl-0.1.2 pygbag-0.9.2 pygments-2.18.0 rich-13.9.4 ruff-0.8.4
(venv) PS D:\projects\python\pydew-valley-uzh> pip install -r requirements-test.txt
Collecting pytest==8.3 (from -r requirements-test.txt (line 1))
  Using cached pytest-8.3.0-py3-none-any.whl.metadata (7.5 kB)
Collecting tox==4.16 (from -r requirements-test.txt (line 2))
  Using cached tox-4.16.0-py3-none-any.whl.metadata (5.0 kB)
Collecting pytest-cov==5.0.0 (from -r requirements-test.txt (line 3))
  Using cached pytest_cov-5.0.0-py3-none-any.whl.metadata (27 kB)
Collecting iniconfig (from pytest==8.3->-r requirements-test.txt (line 1))
  Using cached iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Collecting packaging (from pytest==8.3->-r requirements-test.txt (line 1))
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pluggy<2,>=1.5 (from pytest==8.3->-r requirements-test.txt (line 1))
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting colorama (from pytest==8.3->-r requirements-test.txt (line 1))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting cachetools>=5.3.3 (from tox==4.16->-r requirements-test.txt (line 2))
  Using cached cachetools-5.5.0-py3-none-any.whl.metadata (5.3 kB)
Collecting chardet>=5.2 (from tox==4.16->-r requirements-test.txt (line 2))
  Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Collecting filelock>=3.15.4 (from tox==4.16->-r requirements-test.txt (line 2))
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting platformdirs>=4.2.2 (from tox==4.16->-r requirements-test.txt (line 2))
  Using cached platformdirs-4.3.6-py3-none-any.whl.metadata (11 kB)
Collecting pyproject-api>=1.7.1 (from tox==4.16->-r requirements-test.txt (line 2))
  Using cached pyproject_api-1.8.0-py3-none-any.whl.metadata (2.7 kB)
Collecting virtualenv>=20.26.3 (from tox==4.16->-r requirements-test.txt (line 2))
  Using cached virtualenv-20.28.0-py3-none-any.whl.metadata (4.4 kB)
Collecting coverage>=5.2.1 (from coverage[toml]>=5.2.1->pytest-cov==5.0.0->-r requirements-test.txt (line 3))
  Using cached coverage-7.6.10-cp313-cp313-win_amd64.whl.metadata (8.4 kB)
Collecting distlib<1,>=0.3.7 (from virtualenv>=20.26.3->tox==4.16->-r requirements-test.txt (line 2))
  Using cached distlib-0.3.9-py2.py3-none-any.whl.metadata (5.2 kB)
Using cached pytest-8.3.0-py3-none-any.whl (341 kB)
Using cached tox-4.16.0-py3-none-any.whl (156 kB)
Using cached pytest_cov-5.0.0-py3-none-any.whl (21 kB)
Using cached cachetools-5.5.0-py3-none-any.whl (9.5 kB)
Using cached chardet-5.2.0-py3-none-any.whl (199 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached coverage-7.6.10-cp313-cp313-win_amd64.whl (211 kB)
Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached platformdirs-4.3.6-py3-none-any.whl (18 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached pyproject_api-1.8.0-py3-none-any.whl (13 kB)
Using cached virtualenv-20.28.0-py3-none-any.whl (4.3 MB)
Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Using cached distlib-0.3.9-py2.py3-none-any.whl (468 kB)
Installing collected packages: distlib, pluggy, platformdirs, packaging, iniconfig, filelock, coverage, colorama, chardet, cachetools, virtualenv, pytest, pyproject-api, tox, pytest-cov
Successfully installed cachetools-5.5.0 chardet-5.2.0 colorama-0.4.6 coverage-7.6.10 distlib-0.3.9 filelock-3.16.1 iniconfig-2.0.0 packaging-24.2 platformdirs-4.3.6 pluggy-1.5.0 pyproject-api-1.8.0 pytest-8.3.0 pytest-cov-5.0.0 tox-4.16.0 virtualenv-20.28.0
(venv) PS D:\projects\python\pydew-valley-uzh> python main.py
pygame-ce 2.5.0 (SDL 2.30.3, Python 3.13.1)
Traceback (most recent call last):
  File "D:\projects\python\pydew-valley-uzh\main.py", line 18, in <module>
    from src.client import send_telemetry
  File "D:\projects\python\pydew-valley-uzh\src\client.py", line 5, in <module>
    import requests  # type: ignore[import-untyped]
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'requests'
(venv) PS D:\projects\python\pydew-valley-uzh>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by LittleWondersHandicraft** [comment]
I forgot to mention:
* the version of my operating system: **Windows 11 Home**
* the version of Python: **Python 3.13.1**

**Comment by HubertReX** [comment]
Hi @LittleWondersHandicraft,

thanks for reporting this. It has been fixed after PR #263 was merged. Can you please confirm?

**Comment by LittleWondersHandicraft** [comment]
I have verified this. It works right for me. I have attached the logs below.

```powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS D:\projects\python\pydew-valley-uzh> git status
On branch main
Your branch is up to date with 'origin/main'.
nothing to commit, working tree clean
PS D:\projects\python\pydew-valley-uzh> git pull
Updating ac7330e..1dd08f9
Fast-forward
 data/maps/town.tmx               |  48 ++++++++++++++-
 data/textboxes/de/dialogues.json |  12 ++--
 data/textboxes/en/dialogues.json |  14 +++--
 data/translations/de.txt         |   3 +-
 data/translations/en.txt         |   3 +-
 main.py                          |  62 +++++++++++++++----
 src/controls.py                  |   3 +-
 src/enums.py                     |   3 +-
 src/screens/game_map.py          |   2 +
 src/screens/level.py             | 125 +++++++++++++++++++++++++++++++++------
 10 files changed, 232 insertions(+), 43 deletions(-)
PS D:\projects\python\pydew-valley-uzh> python -m venv venv
PS D:\projects\python\pydew-valley-uzh> venv\Scripts\activate
(venv) PS D:\projects\python\pydew-valley-uzh> pip install -r requirements.txt
Collecting PyTMX==3.32 (from -r requirements.txt (line 1))
  Using cached PyTMX-3.32-py3-none-any.whl.metadata (1.0 kB)
Collecting pathfinding==1.0.10 (from -r requirements.txt (line 2))
  Using cached pathfinding-1.0.10-py3-none-any.whl.metadata (4.6 kB)
Collecting pygame-ce==2.5.0 (from -r requirements.txt (line 3))
  Using cached pygame_ce-2.5.0-cp313-cp313-win_amd64.whl
Collecting requests==2.32.3 (from -r requirements.txt (line 4))
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting openpyxl==3.1.5 (from -r requirements.txt (line 6))
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting charset-normalizer<4,>=2 (from requests==2.32.3->-r requirements.txt (line 4))
  Using cached charset_normalizer-3.4.1-cp313-cp313-win_amd64.whl.metadata (36 kB)
Collecting idna<4,>=2.5 (from requests==2.32.3->-r requirements.txt (line 4))
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests==2.32.3->-r requirements.txt (line 4))
  Using cached urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests==2.32.3->-r requirements.txt (line 4))
  Using cached certifi-2024.12.14-py3-none-any.whl.metadata (2.3 kB)
Collecting et-xmlfile (from openpyxl==3.1.5->-r requirements.txt (line 6))
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached PyTMX-3.32-py3-none-any.whl (24 kB)
Using cached pathfinding-1.0.10-py3-none-any.whl (22 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached certifi-2024.12.14-py3-none-any.whl (164 kB)
Using cached charset_normalizer-3.4.1-cp313-cp313-win_amd64.whl (102 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.3.0-py3-none-any.whl (128 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: pathfinding, urllib3, PyTMX, pygame-ce, idna, et-xmlfile, charset-normalizer, certifi, requests, openpyxl
Successfully installed PyTMX-3.32 certifi-2024.12.14 charset-normalizer-3.4.1 et-xmlfile-2.0.0 idna-3.10 openpyxl-3.1.5 pathfinding-1.0.10 pygame-ce-2.5.0 requests-2.32.3 urllib3-2.3.0
(venv) PS D:\projects\python\pydew-valley-uzh> pip install -r requirements-dev.txt
Collecting ruff~=0.5 (from -r requirements-dev.txt (line 1))
  Downloading ruff-0.8.6-py3-none-win_amd64.whl.metadata (25 kB)
Collecting pygbag==0.9.2 (from -r requirements-dev.txt (line 2))
  Using cached pygbag-0.9.2-py3-none-any.whl.metadata (7.4 kB)
Collecting rich==13.9.4 (from -r requirements-dev.txt (line 3))
  Using cached rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting markdown-it-py>=2.2.0 (from rich==13.9.4->-r requirements-dev.txt (line 3))
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich==13.9.4->-r requirements-dev.txt (line 3))
  Downloading pygments-2.19.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich==13.9.4->-r requirements-dev.txt (line 3))
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached pygbag-0.9.2-py3-none-any.whl (171 kB)
Using cached rich-13.9.4-py3-none-any.whl (242 kB)
Downloading ruff-0.8.6-py3-none-win_amd64.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 10.6 MB/s eta 0:00:00
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Downloading pygments-2.19.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 8.9 MB/s eta 0:00:00
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: ruff, pygments, pygbag, mdurl, markdown-it-py, rich
Successfully installed markdown-it-py-3.0.0 mdurl-0.1.2 pygbag-0.9.2 pygments-2.19.0 rich-13.9.4 ruff-0.8.6
(venv) PS D:\projects\python\pydew-valley-uzh> pip install -r requirements-test.txt
Collecting pytest==8.3 (from -r requirements-test.txt (line 1))
  Using cached pytest-8.3.0-py3-none-any.whl.metadata (7.5 kB)
Collecting tox==4.16 (from -r requirements-test.txt (line 2))
  Using cached tox-4.16.0-py3-none-any.whl.metadata (5.0 kB)
Collecting pytest-cov==5.0.0 (from -r requirements-test.txt (line 3))
  Using cached pytest_cov-5.0.0-py3-none-any.whl.metadata (27 kB)
Collecting iniconfig (from pytest==8.3->-r requirements-test.txt (line 1))
  Using cached iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Collecting packaging (from pytest==8.3->-r requirements-test.txt (line 1))
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pluggy<2,>=1.5 (from pytest==8.3->-r requirements-test.txt (line 1))
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting colorama (from pytest==8.3->-r requirements-test.txt (line 1))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting cachetools>=5.3.3 (from tox==4.16->-r requirements-test.txt (line 2))
  Using cached cachetools-5.5.0-py3-none-any.whl.metadata (5.3 kB)
Collecting chardet>=5.2 (from tox==4.16->-r requirements-test.txt (line 2))
  Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Collecting filelock>=3.15.4 (from tox==4.16->-r requirements-test.txt (line 2))
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting platformdirs>=4.2.2 (from tox==4.16->-r requirements-test.txt (line 2))
  Using cached platformdirs-4.3.6-py3-none-any.whl.metadata (11 kB)
Collecting pyproject-api>=1.7.1 (from tox==4.16->-r requirements-test.txt (line 2))
  Using cached pyproject_api-1.8.0-py3-none-any.whl.metadata (2.7 kB)
Collecting virtualenv>=20.26.3 (from tox==4.16->-r requirements-test.txt (line 2))
  Downloading virtualenv-20.28.1-py3-none-any.whl.metadata (4.5 kB)
Collecting coverage>=5.2.1 (from coverage[toml]>=5.2.1->pytest-cov==5.0.0->-r requirements-test.txt (line 3))
  Using cached coverage-7.6.10-cp313-cp313-win_amd64.whl.metadata (8.4 kB)
Collecting distlib<1,>=0.3.7 (from virtualenv>=20.26.3->tox==4.16->-r requirements-test.txt (line 2))
  Using cached distlib-0.3.9-py2.py3-none-any.whl.metadata (5.2 kB)
Using cached pytest-8.3.0-py3-none-any.whl (341 kB)
Using cached tox-4.16.0-py3-none-any.whl (156 kB)
Using cached pytest_cov-5.0.0-py3-none-any.whl (21 kB)
Using cached cachetools-5.5.0-py3-none-any.whl (9.5 kB)
Using cached chardet-5.2.0-py3-none-any.whl (199 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached coverage-7.6.10-cp313-cp313-win_amd64.whl (211 kB)
Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached platformdirs-4.3.6-py3-none-any.whl (18 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached pyproject_api-1.8.0-py3-none-any.whl (13 kB)
Downloading virtualenv-20.28.1-py3-none-any.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 10.9 MB/s eta 0:00:00
Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Using cached distlib-0.3.9-py2.py3-none-any.whl (468 kB)
Installing collected packages: distlib, pluggy, platformdirs, packaging, iniconfig, filelock, coverage, colorama, chardet, cachetools, virtualenv, pytest, pyproject-api, tox, pytest-cov
Successfully installed cachetools-5.5.0 chardet-5.2.0 colorama-0.4.6 coverage-7.6.10 distlib-0.3.9 filelock-3.16.1 iniconfig-2.0.0 packaging-24.2 platformdirs-4.3.6 pluggy-1.5.0 pyproject-api-1.8.0 pytest-8.3.0 pytest-cov-5.0.0 tox-4.16.0 virtualenv-20.28.1
(venv) PS D:\projects\python\pydew-valley-uzh> python main.py
pygame-ce 2.5.0 (SDL 2.30.3, Python 3.13.1)
Game version 1
Level 1
(venv) PS D:\projects\python\pydew-valley-uzh>
```
